// <auto-generated />
using System;
using HelloWorldWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelloWorldWebApp.Migrations
{
	[DbContext(typeof(HelloWorldWebAppContext))]
	partial class HelloWorldWebAppContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "6.0.15")
				.HasAnnotation("Relational:MaxIdentifierLength", 128);

			SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

			modelBuilder.Entity("HelloWorldWebApp.Models.Movie", b =>
				{
					b.Property<int>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("int");

					SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

					b.Property<string>("Genre")
						.HasColumnType("nvarchar(max)");

					b.Property<decimal>("Price")
						.HasColumnType("decimal(18,2)");

					b.Property<DateTime>("ReleaseDate")
						.HasColumnType("datetime2");

					b.Property<string>("Title")
						.HasColumnType("nvarchar(max)");

					b.HasKey("Id");

					b.ToTable("Movie");
				});
#pragma warning restore 612, 618
		}
	}
}
